### ISSUE TITLE
On Windows, keyring password size is limited, quickly leading to OSError: [WinError 1783] The stub received bad data.

### ISSUE THREAD

**Issue by greywidget** [glyph/PINPal#1]
## Description
I was just playing with PinPal in a venv and received an error.

I set up one PinPal secret with `pinpal new` and ran `pinpal` a couple of times to try it - I got prompted as expected.
I set up a second PinPal secret, ran PinPal and got prompted for them both as expected.

I logged off for a while, then some hours later logged back on for another reminder. On running `pinpal` I got a prompt for the first secret which was accepted. I got a prompt for the second secret and after I entered it, the following exception occurred (and keeps occurring:)

## Error Log
```
pinpal


testme (reminder: octane utilisation):
yay
2 correct entries to go before leveling up


woody (reminder: protection mitochondrial):
yay
3 correct entries to go before leveling up
Traceback (most recent call last):
  File "C:\Users\Craig\python_projects\play\venv\Lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 33, in pywin32error
    yield
  File "C:\Users\Craig\python_projects\play\venv\Lib\site-packages\win32ctypes\pywin32\win32cred.py", line 35, in CredWrite
    _authentication._CredWrite(c_pcreds, 0)
  File "C:\Users\Craig\python_projects\play\venv\Lib\site-packages\win32ctypes\core\ctypes\_util.py", line 61, in check_false
    raise make_error(function, function_name)
OSError: [WinError 1783] The stub received bad data.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Craig\python_projects\play\venv\Scripts\pinpal.exe\__main__.py", line 7, in <module>
  File "C:\Users\Craig\python_projects\play\venv\Lib\site-packages\pinpal.py", line 645, in main
    app.save()
  File "C:\Users\Craig\python_projects\play\venv\Lib\site-packages\pinpal.py", line 590, in save
    set_password(
  File "C:\Users\Craig\python_projects\play\venv\Lib\site-packages\keyring\core.py", line 61, in set_password
    get_keyring().set_password(service_name, username, password)
  File "C:\Users\Craig\python_projects\play\venv\Lib\site-packages\keyring\backends\Windows.py", line 128, in set_password
    self._set_password(service, username, str(password))
  File "C:\Users\Craig\python_projects\play\venv\Lib\site-packages\keyring\backends\Windows.py", line 139, in _set_password
    win32cred.CredWrite(credential, 0)
  File "C:\Users\Craig\python_projects\play\venv\Lib\site-packages\win32ctypes\pywin32\win32cred.py", line 34, in CredWrite
    with _pywin32error():
  File "C:\Users\Craig\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Craig\python_projects\play\venv\Lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (1783, 'CredWrite', 'The stub received bad data.')
```

## Environment
- Windows 10
- Python3.11.5 in a venv
- Top level Packages in the environment:
```
python -m pip list --not-required
Package        Version
-------------- ---------
beautifulsoup4 4.11.2
pinpal         2023.4.22
pip-tools      7.3.0
shellingham    1.5.4
streamlit      1.28.1
typer          0.9.0
```

Thankyou for taking the time to write this utility. If you need any more info please let me know.

**Comment by glyph** [comment]
Thanks for filing the first bug on PinPal!

I don't have a Windows 10 installation and I haven't tested this extensively on any non-macOS platform, but it *should* work.

It's possible that the issue here is that the secret grows each time you interact with PinPal; it appends to a list of timestamps in a JSON blob, and never rolls any off the end.  I tested that very large secrets can be stored by the macOS default `keyring` backend (i.e. the macOS keychain), but I have not performed similar tests on Windows.

Would you be able to try `keyring set` and `keyring get` CLI tools, with very large strings, to see if just a basic keyring interaction can provoke the same problem? When I have some time I can try this on my Windows 11 VM, but I'd be curious to hear about results from your system since Windows can be quite variable and finicky, especially between major versions.

Thanks again!

**Comment by greywidget** [comment]
Hiya - thanks for your quick response.

Sure thing - I'll have a play with the `keyring` CLI and see if I can determine the storage limits - that does seem a likely cause of the issue. I'll report back soon.

Also - thanks for your TalkPython appearance and PyCon talk - I enjoyed them both and appreciated your knowledge, information and humour. I had been wanting a better secrets solution for a while.

Nice one.
PS I hope you're having a nice festive break.

**Comment by glyph** [comment]
Some sleuthing revealed [this bug report](https://github.com/Azure/azure-sdk-for-python/issues/9857):

> keyring.set_password() fails on Windows with a 1281 character password, with the (1783, 'CredWrite', 'The stub received bad data') message, but succeeds with 1280 characters.

so it looks like our length limit is 1280. PINPal will need to be more careful in its assumptions about storage secret size. In the meanwhile you might be able to work around this with a different keyring backend configuration.

**Comment by greywidget** [comment]
Nice sleuthage...

```
import keyring
from rich.progress import track


MAXLEN = 1300

for i in track(range(1, MAXLEN + 1), description="[green]Updating Password..."):
    data = "#" * i
    try:
        keyring.set_password("cred_man", "len_test", data)
    except Exception as e:
        print(f"Exception: {type(e)} {e}")
        print(f"Failed with length {i}")
        break

stored_data = keyring.get_password("cred_man", "len_test")
print(f"Successfully stored <{stored_data}>\nLength: {len(stored_data)}")
keyring.delete_password("cred_man", "len_test")
```

- I can confirm that 1280 is the max character length on Windows 10:
- I ran a couple of tests on my new M2 (Ventura) and haven't hit the limit yet. My last test was 50,000 which worked OK.
- My (very) old MacBook which won't upgrade past Catalina also worked fine with 50,000 although it did take 42 minutes to run the test...
- I'm a bit of a newby with regards to Linux. I'd like be able to use `keyring` with WSL2 on Windows 10 and also in Docker, but I think I need to do a bit more investigation to figure out the best Backend to use and how to get it installed properly. `keyring` seems to suggest KWallet which relies on [dbus](https://pypi.org/project/dbus-python/) whose release is more than a year old and states: 

> dbus-python might not be the best D-Bus binding for you to use

**Comment by greywidget** [comment]
When I first saw this error (on Windows), I had added 2 passwords to `pinpal`.  

Out of curiousity, I wondered if the limited storage available when using the default Credential Manager on Windows might be enough for a single password, but that's not the case - I removed previous passwords with `keyring` and then set up a new one using `pinpal`. It abended when I levelled up and it tried to append a fourth word.

I'm sure you already know this, but I thought I'd mention it since I was able to test it.

**Comment by glyph** [comment]
Thanks for confirming. Now we just need to do something smarter for its storage ;)

One possibility is to store nothing but a randomly-generated encryption key in the keyring and stick everything into a Fernet encrypted file.
